spring.application.name=HorusBack

# MySQL Configuration
spring.datasource.url=jdbc:mysql://5.tcp.ngrok.io:29865/bdhorus?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=horusback
spring.datasource.password=Tiburonlimon2026$
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
